# Generated by Django 6.1 on 2026-09-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='category',
            field=models.CharField(blank=True, choices=[('burgers', 'Burgers'), ('pizza', 'Pizza'), ('chinese', 'Chinese'), ('drinks', 'Drinks'), ('desserts', 'Desserts'), ('rajasthani', 'Rajasthani'), ('hot_drinks', 'Hot Drinks'), ('cake', 'Cake')], max_length=30, null=True),
        ),
    ]
