# Generated by Django 6.1 on 2026-09-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_fooditem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='category',
            field=models.CharField(blank=True, choices=[('burger', 'Burgers'), ('pizza', 'Pizza'), ('chinese', 'Chinese'), ('drink', 'Drinks'), ('desserts', 'Desserts'), ('rajasthani', 'Rajasthani'), ('hot-drinks', 'Hot Drinks'), ('cake', 'Cake'), ('sandwich', 'Sandwich'), ('sweets', 'Sweets')], max_length=30, null=True),
        ),
    ]
